apiVersion: v1
kind: Namespace
metadata:
  name: hayat
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hayat
  namespace: hayat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hayat-role
  namespace: hayat
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
